import React, { useState } from "react";
import { IoMdAdd, IoMdRemove } from "react-icons/io";
import { motion } from "framer-motion";

const IntelliFaqs = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleAnswer = (index: any) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      id: 1,
      question: "Is the content unique?",
      answer:
        "95% of the content generated by the AI is unique and original. We also provide a uniqueness score for longer form content generated so you can have peace of mind to know that the content you have received is unique.",
    },
    {
      id: 2,
      question: "How is the content generated?",
      answer:
        "We make use of a variety of AI models, with Generative Pre-trained Transformer 3 is an autoregressive language model which uses deep learning to produce human-like text. It's a game changer for content creators.",
    },
    {
      id: 3,
      question: "Who retains the copyright?",
      answer:
        "You do. We will not claim copyright over content generated by the AI for you.",
    },
    {
      id: 4,
      question: "What languages do you support?",
      answer:
        "We currently support all languages supported by Google Translate.",
    },
    {
      id: 5,
      question: "Is there discount for non-profits?",
      answer: "Please get in touch with us below.",
    },
  ];
  return (
    <div className="relative w-full bg-transparent px-4  font-inter py-10">
      <div className="w-full max-w-6xl mx-auto flex flex-col gap-10 items-center justify-center">
        <div className="flex flex-col items-center justify-center max-w-4xl text-white gap-3 px-3">
          {/* TITLE */}
          <h2
            className="text-2xl md:text-3xl lg:text-4xl font-bold text-transparent bg-clip-text"
            style={{
              backgroundImage:
                "linear-gradient(81.88deg, #BFAAFF 0%, #F64CFF 78%, #FFC553 100%)",
            }}
          >
            Got Questions? We’ve Got Answers!
          </h2>

          <p className="font-extralight text-center text-sm">
            We&apos;re dedicated to assisting individuals interested in
            generating AI-driven content and images.
          </p>
        </div>

        <div className="w-full flex flex-col gap-5">
          {faqs.map((item, index) => (
            <div key={index}>
              {/* Question Section */}
              <div
                className="flex flex-col items-center justify-between px-5 py-4 bg-[#1B1337] border-2 h-auto text-white cursor-pointer"
                style={{
                  borderImage:
                    "linear-gradient(to right, #6B41FF 50%, #F64CFF 80%, #FFC553 100%)  1% round",
                }}
                onClick={() => toggleAnswer(index)}
              >
                <div className="w-full flex justify-between items-center text-base xl:text-lg">
                  {item.question}

                  {/* Animated Icon */}
                  <motion.div
                    animate={{ rotate: openIndex === index ? 180 : 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    {openIndex === index ? (
                      <IoMdRemove size={20} />
                    ) : (
                      <IoMdAdd size={20} />
                    )}
                  </motion.div>
                </div>

                {/* Answer Section */}
                <motion.div
                  initial={false}
                  animate={{
                    maxHeight: openIndex === index ? "300px" : "0px",
                    opacity: openIndex === index ? 1 : 0,
                  }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                  className="overflow-hidden w-full"
                >
                  <div className="px-0 py-2 mt-4 text-left bg-[#1b1337af] border-t !border-[#433C5A] h-auto text-white">
                    {item.answer}
                  </div>
                </motion.div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default IntelliFaqs;
